core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^me$', views.me, name='user_details'),
]

polls/urls.py
from django.conf.urls import url

from polls.views import DetailView, IndexView, results, vote

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='polls_list'),
    url(r'^(?P<pk>[0-9]+)/$', DetailView.as_view(), name='poll_detail'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', vote, name='vote'),
    url(r'^(?P<question_id>[0-9]+)/results/$', results, name='results'),

]

referendum/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView
from registration.backends.simple.views import RegistrationView

from core.forms import CustomUserCreationForm

urlpatterns = [
    url(r'^', include('core.urls')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^register/$',
        RegistrationView.as_view(
            form_class=CustomUserCreationForm
        ),
        name='registration_register',
        ),
    url(r'^', include('registration.backends.simple.urls')),
]

users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^me$', views.me, name='user_details'),
]

core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    email = models.EmailField(_('email address'), unique=True)

    def get_email(self):
        return self.email


class UserProfile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='profile'
    )
    bio = models.TextField(max_length=500, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    first_name = models.CharField(_('first name'), max_length=60, blank=True)
    last_name = models.CharField(_('last name'), max_length=60, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

polls/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from core.models import UserProfile


class Question(models.Model):
    question = models.CharField(_('question'), max_length=200, blank=False)
    description = models.TextField(_('description'), max_length=500, blank=True)
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(_('choice'), max_length=200)
    votes = models.IntegerField(default=0)
    voters = models.ManyToManyField(UserProfile, through='Vote',
                                    through_fields=('choice', 'voter'))


class Vote(models.Model):
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    voter = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, default=1)
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)

core/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from registration.forms import RegistrationForm

from core.models import UserProfile


class CustomUserCreationForm(RegistrationForm):
    email = forms.EmailField(required=True)

    class Meta(RegistrationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"].lower()
        if commit:
            user.save()
        return user


class AccountProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'bio', 'birth_date']

core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from core.forms import AccountProfileForm


@login_required(login_url='/login')
def me(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = AccountProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
    else:
        form = AccountProfileForm()
    return render(request, 'account/user_details.html', {'form': form})

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from polls.models import Question, Choice, Vote


class IndexView(generic.ListView):
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-created_at')[:5]


class DetailView(generic.DetailView):
    model = Question


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/question_detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
         if len(Vote.objects.filter(
                 question_id=selected_choice.question.id,
                 voter_id=request.user.id)) > 0:
             return render(request, 'polls/question_detail.html', {
                 'question': question,
                 'error_message': "Vous avez déjà voté pour cette question",
             })

         user_vote = Vote()
         user_vote.voter = request.user.profile
         user_vote.choice = selected_choice
         user_vote.question = selected_choice.question
         user_vote.save()
         selected_choice.votes += 1
         selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
         return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/question_results.html', {'question': question})

polls/templates/polls/question_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ question.question }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}
        <input type="submit" value="Vote" />
    </form>
{% endblock %}

polls/templates/polls/question_list.html
{% extends "base.html" %}

{% block content %}
    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li><a href="/polls/{{ question.id }}/">{{ question.question }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/question_results.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ question.question }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% for choice in question.choice_set.all %}
        <p>{{ choice.choice_text }}: {{ choice.votes }}</p><br />
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Referendum{% endblock %}</title>
    {% load static %}
    <!-- Bootstrap core CSS-->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/referendum.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">

    {% block css %}
    {% endblock %}

</head>
<body>
{% block body %}
    <header>
        {% include "navbar.html" %}
    </header>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    <!-- Bootstrap core JavaScript
================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/vendor/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Login{% endblock %}

{% block content %}
    <h2>{% trans "Home" %}</h2>
{% endblock %}

templates/navbar.html
{% load i18n %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'home' %}">Referendum</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto flex-row"></ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'user_details' %}">
                        <i class="fa fa-user-circle-o" aria-hidden="true"></i> {% trans 'Hello' %}
                        {% if user.profile.first_name %} {{ user.profile.first_name }} {% else %} {{ user.username }} {% endif %}
                    </a>
                </li>
                <li>
                    <a class="btn btn-danger nav-link" href="{% url 'auth_logout' %}">{% trans 'Log out' %}</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth_login' %}">{% trans 'Log in' %}</a>
                </li>
                <li class="nav-item active">
                <a class="nav-link active" href="{% url 'registration_register' %}">{% trans 'Sign up' %}</a>
                </li>
            {% endif %}
        </ul>
    </div>

</nav>